name: VerifyIssue

on:
  pull_request:
    types: [edited, synchronize, opened, reopened]
  check_run:

jobs:
  verify_linked_issue:
    runs-on: ubuntu-latest
    name: PR has a linked issue.
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Verify Linked Issue
        uses: ./ 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
